# -*- coding: utf-8 -*-
"""content-selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xtTj05CiHOFfockT_aAN7_p0UlScvWUc
"""

from summa import summarizer
import matplotlib.pyplot as plt
import pandas as pd

data_df = pd.read_csv('../preprocessed_data/merged_prefix_transcript_description_summ.tsv.zip', sep='\t', header=0, encoding='utf-8')
sampled_df = data_df.sample(frac=0.1)
sampled_df = sampled_df.drop('Unnamed: 0', 1)
sampled_df

sampled_df['n_sentences'] = sampled_df['episode_transcript'].apply(lambda x: x.count('.'))
sampled_df

def text_rank_selection(transcript, n=300):
    return summarizer.summarize(transcript, ratio=5/float(n)).replace('\n', ' ')
#     return summarizer.summarize(transcript, ratio=0.1).replace('\n', ' ')

data_dict = sampled_df.to_dict('records')

for i,data_entry in enumerate(data_dict):
    data_entry['episode_transcript'] = text_rank_selection(data_entry['episode_transcript'], data_entry['n_sentences'])
    data_dict[i] = data_entry
    if (i + 1) % 100 == 0:
        print(i)
#         break

data_dict[:100]

textranked_df = pd.DataFrame(data_dict)
textranked_df.rename(columns={'episode_transcript': 'episode_transcript_textranked'}, inplace=True)
textranked_df.to_csv('../preprocessed_data/merged_prefix_transcriptTextRanked_description_summ_10k.tsv', sep='\t')

